### PR TITLE
Update SimulatedHttpRequest.cs

### PR DESCRIPTION
**Pull request by KroniKZA**
Updated GetKnownRequestHeader to return Accept-Language header for Request.UserLanguages support.

### CODE REVIEW

**Comment by MattDavies** [comment]
Hi guys,

Apologies, I hadn't seen any messages come through!

Just got pointed to this thread - I've added you @ferronrsmith.

Thanks

**Comment by ferronrsmith** [comment]
Thank a lot.

Sent from my iPhone

**Comment by KroniKZA** [comment]
Hey,

@ferronrsmith - Any idea when the nuget package will be updated?

Thanks

**Comment by KroniKZA** [comment]
@ferronrsmith - Never mind, just saw now that it has been updated. Thanks!

**Comment by ferronrsmith** [comment]
It's already up. I did it a few hours ago.

On Wed, May 13, 2015 at 3:56 AM, KroniKZA <notifications@github.com> wrote:

> Hey,
>
> @ferronrsmith <https://github.com/ferronrsmith> - Any idea when the nuget
> package will be updated?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ferronrsmith/httpcontext-simulator/pull/4#issuecomment-101557482>
> .
>



-- 
"*Give me a place to stand* on, *and I will move the Earth*."

Ferron Hanse

**Comment by cottsak** [comment]
This is awesome! An update to the package ~4 years later! // @MattDavies

**Pull request merged**
