### PR TITLE
additional features request cookie, browser capabilities, logon user identity

### PR DESCRIPTION
**Pull request by rferstl**
Hi ferron,

I use your http simulator with great success to perform unit tests for a legacy product for which we develop plugins that are tightly coupled to the HttpContext. To perform the unit tests, I need the features in this pull request. It would be great if the features were added to your library.

Best regards Roland

### CODE REVIEW

**Comment by rferstl** [comment]
I will retry after test with mono

**Comment by ferronrsmith** [comment]
Let me know when you’re ready to merge. Thanks for your submission

**Comment by rferstl** [comment]
travis build for mono 3.12 and 3.10 run into error -> see issue #14 
Thanks Roland

**Comment by ferronrsmith** [comment]
Yea that error is weird. I'll try running it locally and see if I get the same errors.

**Comment by ferronrsmith** [comment]
merged into #16

**Pull request closed without merging**
